name: Create, publish and deploy project
on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ollama

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release name
        id: release_name
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const branch_name = process.env.GITHUB_REF
            const release_version = branch_name.substring(branch_name.lastIndexOf('/') +1 ,branch_name.length  )
            process.env.VERSION = release_version
            return release_version

      - name: Build and push Flask app Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:flask-app-latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:flask-app-v${{ steps.release_version.outputs.version }}
